In [4]:
import numpy as np

# 1. Matriks Reward (R) sesuai denah
R = np.array([
    [-1, -1, -1, -1,  0, -1],  # Ruangan 0
    [-1, -1, -1,  0, -1, 100], # Ruangan 1
    [-1, -1, -1,  0, -1, -1],  # Ruangan 2
    [-1,  0,  0, -1,  0, -1],  # Ruangan 3
    [ 0, -1, -1,  0, -1, 100], # Ruangan 4
    [-1,  0, -1, -1,  0, 100]  # Ruangan 5 (Goal State)
])

# 2. Inisialisasi Tabel Q dengan 0
Q = np.zeros([6, 6])
gamma = 0.8
episodes = 10

print("=== MEMULAI SIMULASI 10 EPISODE (SKALA REFERENSI 100) ===\n")

# 3. Proses Perulangan per Episode
for episode in range(1, episodes + 1):
    # Pilih ruangan acak sebagai titik awal agen
    current_state = np.random.randint(0, 6)
    start_state = current_state
    jalur_dilewati = []

    while True:
        # Cari pintu yang tersedia
        available_actions = np.where(R[current_state] >= 0)[0]
        # Agen memilih tindakan secara acak (Exploration)
        action = int(np.random.choice(available_actions))

        # Catat langkah agen
        jalur_dilewati.append(f"{current_state}➔{action}")

        # Rumus utama Q-Learning (Bellman Equation)
        Q[current_state, action] = R[current_state, action] + gamma * np.max(Q[action])

        # Selesai jika agen berhasil keluar (mencapai ruangan 5)
        if action == 5:
            break
        current_state = action

    # 4. Proses Normalisasi ke Skala 100 (Agar sama dengan gambar referensi)
    max_val = np.max(Q)
    if max_val > 0:
        Q_normalized = (Q / max_val) * 100
    else:
        Q_normalized = Q

    # 5. Tampilkan detail hasil setiap episode
    print(f"➔ EPISODE {episode} (Titik Start: Ruangan {start_state})")
    print(f"   Rute Langkah : " + " , ".join(jalur_dilewati))
    print("   Kondisi Tabel Q Saat Ini:")
    print(Q_normalized.astype(int))
    print("-" * 65 + "\n")

=== MEMULAI SIMULASI 10 EPISODE (SKALA REFERENSI 100) ===

➔ EPISODE 1 (Titik Start: Ruangan 3)
   Rute Langkah : 3➔4 , 4➔5
   Kondisi Tabel Q Saat Ini:
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]]
-----------------------------------------------------------------

➔ EPISODE 2 (Titik Start: Ruangan 2)
   Rute Langkah : 2➔3 , 3➔2 , 2➔3 , 3➔4 , 4➔3 , 3➔4 , 4➔5
   Kondisi Tabel Q Saat Ini:
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0  80   0]
 [  0   0   0  64   0 100]
 [  0   0   0   0   0   0]]
-----------------------------------------------------------------

➔ EPISODE 3 (Titik Start: Ruangan 1)
   Rute Langkah : 1➔5
   Kondisi Tabel Q Saat Ini:
[[  0   0   0   0   0   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]
 [  0   0   0   0  80   0]
 [  0   0   0  64   0 100]
 [  0   0   0   0   0   0]]
------------